### ISSUE TITLE
Unable to test using iPhone

### ISSUE THREAD

**Issue by freelancer-repo** [qqTYXn7/browserprint#2]
After entering the captcha, the screen with a flash component is loaded and then redirected to a new screen that displays the following message: " An error has occurred. "

**Comment by qqTYXn7** [comment]
Hi.
Can you please confirm that this is after a submission to browserprint.info and not your own instance.
Could you please tell me what kind of iPhone you have and what browser you were using?
Do you have anything like non-english languages or any browser extensions installed on your phone?
Could you please submit your fingerprint and give me a rough time (in UTC) of submission?
Thank you

**Comment by freelancer-repo** [comment]
> Can you please confirm that this is after a submission to browserprint.info and not your own instance.

It was after a submission to browserprint.info

> Could you please tell me what kind of iPhone you have and what browser you were using?

iPhone 6s, running Safari on iOS 11 public beta 3

> Do you have anything like non-english languages or any browser extensions installed on your phone?

No and no (extensions aren't allowed in Safari for iOS).

> Could you please submit your fingerprint and give me a rough time (in UTC) of submission?

Around the first comment's time of creation

**Comment by qqTYXn7** [comment]
Could you please try again?
I have fixed a bug but I'm not sure if it's yours.

**Comment by freelancer-repo** [comment]
I've just tried again and it's still going on. Enable debug mode if you can (and need) and I'll paste whatever content from the console

**Comment by qqTYXn7** [comment]
I think I've found the problem.
Please try again.

**Comment by freelancer-repo** [comment]
Yeah, thanks for the quick fix 👍👍👍
